routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
    Route::get('/', 'HomeController@admin')->name('admin');
    Route::resource('/user', 'UserController');
    Route::resource('/post', 'PostController');
    Route::resource('/comment', 'CommentController');
});



Route::get('/user', 'HomeController@user')->name('user');


Route::resource('/frontend', 'FrontendController');
Route::get('/', 'FrontendController@index')->name('homepage');
Route::post('/login1', 'FrontendController@login1')->name('login1');


Route::group(['prefix'=>'user'], function(){
    Route::resource('/userpanel','UserPanelController');
    Route::post('/user_post','UserPanelController@user_post')->name('user_post');
    Route::get('/user_update/{id}','UserPanelController@user_update')->name('user_update');
    Route::post('/user_store/{id}','UserPanelController@user_store')->name('user_store');
    Route::get('/my_post','UserPanelController@my_post')->name('my_post');
    Route::get('/members','UserPanelController@members')->name('members');
    Route::get('/search','UserPanelController@search')->name('search');
    Route::get('/user_details/{id}','UserPanelController@user_details')->name('user_details');
    Route::get('/post_details/{id}','UserPanelController@post_details')->name('post_details');
    Route::post('/insert_comment/{user_id}/{id}','UserPanelController@insert_comment')->name('insert_comment');

    Route::get('/delete_comment/{id}','UserPanelController@delete_comment')->name('delete_comment');

    Route::get('/friends','UserPanelController@friends')->name('friends');

    Route::get('/addfriend/{id}','UserPanelController@addfriend')->name('addfriend');


    Route::get('/cancel_request/{id}','UserPanelController@cancel_request')->name('cancel_request');
    Route::get('/confirm_request/{id}','UserPanelController@confirm_request')->name('confirm_request');

    Route::get('/sendmessage/{id}','UserPanelController@sendmessage')->name('sendmessage');

    Route::post('/insert_message/{id}','UserPanelController@insert_message')->name('insert_message');


});

resources/views/admin/section/footer.blade.php
<footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>

resources/views/admin/section/header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Admin CMS! | </title>

    <!-- Bootstrap -->
    <link href="{{asset('assets/admin/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('assets/admin/css/font-awesome.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('assets/admin/css/nprogress.css')}}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{asset('assets/admin/css/custom.min.css')}}" rel="stylesheet">
  </head>

resources/views/admin/section/menu.blade.php
<div class="profile clearfix">
              <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
              </div>
              <div class="clearfix"></div>
            </div>

resources/views/admin/section/notification.blade.php
@if(session()->has('success'))
<p class="alert alert-success">{{ session('success') }}</p>
@endif


@if(session()->has('error'))
<p class="alert alert-danger">{{ session('error') }}</p>
@endif




<script>
    setTimeout(function(){
        $('.alert').slideUp();
    },3000);
</script>

resources/views/admin/section/scripts.blade.php
  <!-- jQuery -->
  <script src="{{asset('assets/admin/js/jquery.min.js')}}"></script>
    <!-- Bootstrap -->
    <script src="{{asset('assets/admin/js/bootstrap.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('assets/admin/js/fastclick.js')}}"></script>
    <!-- NProgress -->
    <script src="{{asset('assets/admin/js/nprogress.js')}}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{asset('assets/admin/js/custom.js')}}"></script>

    @yield('scripts')

resources/views/admin/section/sidebar.blade.php
   <!-- sidebar menu -->
   <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="{{route('user.index')}}"><i class="fa fa-home"></i> Users <span class="fa fa-chevron-right"></span></a>
                  <li><a href="{{route('post.index')}}"><i class="fa fa-home"></i> Posts <span class="fa fa-chevron-right"></span></a>
                  <li><a href="{{route('comment.index')}}"><i class="fa fa-home"></i> Comments <span class="fa fa-chevron-right"></span></a>
                   
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

resources/views/admin/section/top_nav.blade.php
<div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{Request()->user()->name}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    
                    <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                         <i class="fa fa-sign-out pull-right"></i> Log Out

                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                             </form>

                   
                </li>
              </ul>
            </nav>
          </div>
        </div>