routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
    Route::get('/', 'HomeController@admin')->name('admin');
    Route::resource('/user', 'UserController');
    Route::resource('/post', 'PostController');
    Route::resource('/comment', 'CommentController');
});



Route::get('/user', 'HomeController@user')->name('user');


Route::resource('/frontend', 'FrontendController');
Route::get('/', 'FrontendController@index')->name('homepage');
Route::post('/login1', 'FrontendController@login1')->name('login1');


Route::group(['prefix'=>'user'], function(){
    Route::resource('/userpanel','UserPanelController');
    Route::post('/user_post','UserPanelController@user_post')->name('user_post');
    Route::get('/user_update/{id}','UserPanelController@user_update')->name('user_update');
    Route::post('/user_store/{id}','UserPanelController@user_store')->name('user_store');
    Route::get('/my_post','UserPanelController@my_post')->name('my_post');
    Route::get('/members','UserPanelController@members')->name('members');
    Route::get('/search','UserPanelController@search')->name('search');
    Route::get('/user_details/{id}','UserPanelController@user_details')->name('user_details');
    Route::get('/post_details/{id}','UserPanelController@post_details')->name('post_details');
    Route::post('/insert_comment/{user_id}/{id}','UserPanelController@insert_comment')->name('insert_comment');

    Route::get('/delete_comment/{id}','UserPanelController@delete_comment')->name('delete_comment');

    Route::get('/friends','UserPanelController@friends')->name('friends');

    Route::get('/addfriend/{id}','UserPanelController@addfriend')->name('addfriend');


    Route::get('/cancel_request/{id}','UserPanelController@cancel_request')->name('cancel_request');
    Route::get('/confirm_request/{id}','UserPanelController@confirm_request')->name('confirm_request');

    Route::get('/sendmessage/{id}','UserPanelController@sendmessage')->name('sendmessage');

    Route::post('/insert_message/{id}','UserPanelController@insert_message')->name('insert_message');


});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'content', 'date','topic_id','user_id','image'
    ];

    public function getRules($option='add'){
        return [
            'content'=>'required|string',
            'topic_id'=>'required|string',
            'user_id'=>'required|exists:users,id'
        ];
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected $post=null;
    public function __construct(Post $post)
    {
        $this->post=$post;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=$this->post->orderBy('id','DESC')->get();
        return view('admin.post.index')->with('postdata',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.form');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        $rules=$this->post->getRules();
        $request->validate($rules);
      
        $data=$request->all();
        $data['date']=now();
        $this->post=$this->post->fill($data);
        $this->post->save();
        if($this->post){
            request()->session()->flash('success','Post added successfully');
        }
        else{
            request()->session()->flash('error','Post not added at this time. Please try again');
        }

        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->post=$this->post->find($id);
        if(!$this->post){
            request()->session()->flash('error','Post does not found');
            return redirect()->route('post.index');
        }
        return view('admin.post.form')->with('post_data',$this->post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules=$this->post->getRules();
        $request->validate($rules);
        //dd($request);
        $data=$request->all();
        $this->post= $this->post->find($id);
        $this->post=$this->post->fill($data);
        $this->post->save();

        if($this->post){
            request()->session()->flash('success','post updated successfully');
        }
        else{
            request()->session()->flash('error','post not updated at this time. Please try again');
        }

        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->post =$this->post->find($id);
        if(!$this->post){
            request()->session()->flash('error','post not found');
            return redirect()->route('post.index');
        }
        $del =$this->post->delete();
        if($del){
            request()->session()->flash('success','post deleted successfully');
        }else{
            request()->session()->flash('error','problem while deleting User');
        }
        return redirect()->route('post.index');
    }
}

resources/views/admin/post/form.blade.php
@extends('layouts.admin_dashboard')

@section('scripts')
<script>
    $('#change_password').change(function(){
        var checked =$('#change_password').prop('checked');
        if(checked){
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('hidden');
        }else{
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('hidden');
        }
    });
</script>
@endsection

@section('content')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>User {{ isset($post_data) ? 'update' : 'add'}} </h3>

            </div>

            <div class="title_right">

            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2> User</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                    @if(isset($post_data))
                       {{Form::open(['url'=>route('post.update',$post_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
                            @method('PUT')


                        @else
                       {{Form::open(['url'=>route('post.store'),'class'=>'Form','enctype'=>'multipart/form-data']) }}
                    @endif
                       <div class="form-group row">
                            {{ Form::label('content', 'Content: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::text('content',@$post_data->content ,['class'=>'form-control','id'=>'content']) }}
                                @if($errors->has('content'))
                                <span class="alert-danger">{{ $errors->first('content') }}</span>
                                @endif
                            </div>
                        </div>

                      


                        <div class="form-group row" >
                            {{Form::label('topic_id','Topic Id:',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::number('topic_id',@$post_data->topic_id ,['class'=>'form-control'])}}
                                @if($errors->has('topic_id'))
                                <span class="alert-danger">{{$errors->first('topic_id')}}</span>
                                @endif
                            </div>
                        </div> 

                        <div class="form-group row">
                            {{ Form::label('user_id', 'User id: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::number('user_id',@$post_data->user_id ,['class'=>'form-control','id'=>'user_id']) }}
                                @if($errors->has('user_id'))
                                <span class="alert-danger">{{ $errors->first('user_id') }}</span>
                                @endif
                            </div>
                        </div>

                     

                        <div class="form-group row">
                            {{ Form::label('', ' ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::button('submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                                {{Form::button('reset',['class'=>'btn btn-danger','id'=>'reset','type'=>'reset']) }}
                               
                            </div>
                        </div>



                       {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin_dashboard')

@section('content')
 <!-- page content -->
 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
               <h3>Welcome to post page</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  
              <a href="{{ route('post.create')}}" class="btn btn-success pull-right"><i class="fas fa-plus"></i> Add post</a>
                  <div class="input-group">
                    
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>
            @include('admin.section.notification')

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>User Page</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <th>S.n</th>
                        <th>post id</th>
                        <th>Post content</th>
                        <th>Post date</th>
                        <th>Topic id</th>
                        <th>User id</th>
                        
                        <th>Action</th>
                      </thead>
                      <tbody>
                       
                          @if($postdata)
                          @foreach($postdata as $key=>$data)
                          <tr>
                          <td>{{ $key+1}}</td>
                          <td>{{ $data->id}}</td>
                          <td>{{ $data->content}}</td>
                          <td>{{ $data->date}}</td>
                          <td>{{ $data->topic_id}}</td>
                          <td>{{ $data->user_id}}</td>
                        
                          <td>
                          <a href="{{ route('post.edit',$data->id)}}" style="border-radius: 50%" class="btn btn-success">
                                        <i class="fas fa-pencil-alt"></i></a>
  

                            <form action="{{ route('post.destroy',$data->id)}}" onsubmit="return confirm('Are you sure to delete')" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger" style="border-radius: 50%">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                          </tr>
                          @endforeach
                          @endif
                      
                      </tbody>

                    </table>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

@endsection