routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
    Route::get('/', 'HomeController@admin')->name('admin');
    Route::resource('/user', 'UserController');
    Route::resource('/post', 'PostController');
    Route::resource('/comment', 'CommentController');
});



Route::get('/user', 'HomeController@user')->name('user');


Route::resource('/frontend', 'FrontendController');
Route::get('/', 'FrontendController@index')->name('homepage');
Route::post('/login1', 'FrontendController@login1')->name('login1');


Route::group(['prefix'=>'user'], function(){
    Route::resource('/userpanel','UserPanelController');
    Route::post('/user_post','UserPanelController@user_post')->name('user_post');
    Route::get('/user_update/{id}','UserPanelController@user_update')->name('user_update');
    Route::post('/user_store/{id}','UserPanelController@user_store')->name('user_store');
    Route::get('/my_post','UserPanelController@my_post')->name('my_post');
    Route::get('/members','UserPanelController@members')->name('members');
    Route::get('/search','UserPanelController@search')->name('search');
    Route::get('/user_details/{id}','UserPanelController@user_details')->name('user_details');
    Route::get('/post_details/{id}','UserPanelController@post_details')->name('post_details');
    Route::post('/insert_comment/{user_id}/{id}','UserPanelController@insert_comment')->name('insert_comment');

    Route::get('/delete_comment/{id}','UserPanelController@delete_comment')->name('delete_comment');

    Route::get('/friends','UserPanelController@friends')->name('friends');

    Route::get('/addfriend/{id}','UserPanelController@addfriend')->name('addfriend');


    Route::get('/cancel_request/{id}','UserPanelController@cancel_request')->name('cancel_request');
    Route::get('/confirm_request/{id}','UserPanelController@confirm_request')->name('confirm_request');

    Route::get('/sendmessage/{id}','UserPanelController@sendmessage')->name('sendmessage');

    Route::post('/insert_message/{id}','UserPanelController@insert_message')->name('insert_message');


});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'post_id', 'user_id','comment'
    ];

    public function getRules($option='add'){
        return [
            'post_id'=>'required|exists:posts,id',
            'comment'=>'required|string',
            'user_id'=>'required|exists:users,id'
        ];
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    protected $comment=null;
    public function __construct(Comment $comment)
    {
        $this->comment=$comment;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=$this->comment->orderBy('id','DESC')->get();
        return view('admin.comment.index')->with('commentdata',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.comment.form');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules=$this->comment->getRules();
        $request->validate($rules);
      
        $data=$request->all();
        $data['date']=now();
        $this->comment=$this->comment->fill($data);
        $this->comment->save();
        if($this->comment){
            request()->session()->flash('success','Post added successfully');
        }
        else{
            request()->session()->flash('error','Post not added at this time. Please try again');
        }

        return redirect()->route('comment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //dd($id);
        $this->comment=$this->comment->find($id);
        if(!$this->comment){
            request()->session()->flash('error','Comment does not found');
            return redirect()->route('comment.index');
        }
        return view('admin.comment.form')->with('comment_data',$this->comment);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules=$this->comment->getRules();
        $request->validate($rules);
        //dd($request);
        $data=$request->all();

      
        $this->comment= $this->comment->find($id);
        $this->comment=$this->comment->fill($data);
        $this->comment->save();

        if($this->comment){
            request()->session()->flash('success','User updated successfully');
        }
        else{
            request()->session()->flash('error','User not updated at this time. Please try again');
        }

        return redirect()->route('comment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //dd($id);
        $this->comment =$this->comment->find($id);
      
        if(!$this->comment){
            request()->session()->flash('error','comment not found');
            return redirect()->route('comment.index');
        }
        $del =$this->comment->delete();
        if($del){
            request()->session()->flash('success','comment deleted successfully');
        }else{
            request()->session()->flash('error','problem while deleting User');
        }
        return redirect()->route('comment.index');
    }
}

resources/views/admin/comment/form.blade.php
@extends('layouts.admin_dashboard')

@section('scripts')
<script>
    $('#change_password').change(function(){
        var checked =$('#change_password').prop('checked');
        if(checked){
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('hidden');
        }else{
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('hidden');
        }
    });
</script>
@endsection

@section('content')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>User {{ isset($comment_data) ? 'update' : 'add'}} </h3>

            </div>

            <div class="title_right">

            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2> Comment</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                    @if(isset($comment_data))
                       {{Form::open(['url'=>route('comment.update',$comment_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
                            @method('PUT')


                        @else
                       {{Form::open(['url'=>route('comment.store'),'class'=>'Form','enctype'=>'multipart/form-data']) }}
                    @endif
                       <div class="form-group row">
                            {{ Form::label('comment', 'Comment: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::text('comment',@$comment_data->comment ,['class'=>'form-control','id'=>'comment']) }}
                                @if($errors->has('comment'))
                                <span class="alert-danger">{{ $errors->first('comment') }}</span>
                                @endif
                            </div>
                        </div>

                      


                        <div class="form-group row" >
                            {{Form::label('post_id','Post Id:',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::number('post_id',@$comment_data->post_id ,['class'=>'form-control'])}}
                                @if($errors->has('post_id'))
                                <span class="alert-danger">{{$errors->first('post_id')}}</span>
                                @endif
                            </div>
                        </div> 

                        <div class="form-group row">
                            {{ Form::label('user_id', 'User id: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::number('user_id',@$comment_data->user_id ,['class'=>'form-control','id'=>'user_id']) }}
                                @if($errors->has('user_id'))
                                <span class="alert-danger">{{ $errors->first('user_id') }}</span>
                                @endif
                            </div>
                        </div>

                     

                        <div class="form-group row">
                            {{ Form::label('', ' ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::button('submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                                {{Form::button('reset',['class'=>'btn btn-danger','id'=>'reset','type'=>'reset']) }}
                               
                            </div>
                        </div>



                       {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

@endsection

resources/views/admin/comment/index.blade.php
@extends('layouts.admin_dashboard')

@section('content')
 <!-- page content -->
 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
               <h3>Welcome to comment page</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  
              <a href="{{ route('comment.create')}}" class="btn btn-success pull-right"><i class="fas fa-plus"></i> Add comment</a>
                  <div class="input-group">
                    
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>
            @include('admin.section.notification')

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>User Page</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <th>S.n</th>
                        <th>comment id</th>
                        <th>Post id</th>
                        <th>user id</th>
                        <th>comment</th>
                        <th>Action</th>
                      </thead>
                      <tbody>
                       
                          @if($commentdata)
                          @foreach($commentdata as $key=>$data)
                          <tr>
                          <td>{{ $key+1}}</td>
                          <td>{{ $data->id}}</td>
                          <td>{{ $data->post_id}}</td>
                          <td>{{ $data->user_id}}</td>
                          <td>{{ $data->comment}}</td>    
                         <td>
                         <a href="{{ route('comment.edit',$data->id)}}" style="border-radius: 50%" class="btn btn-success">
                                        <i class="fas fa-pencil-alt"></i></a>
  

                            <form action="{{ route('comment.destroy',$data->id)}}" onsubmit="return confirm('Are you sure to delete')" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger" style="border-radius: 50%">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                         </td>
                            
                          </tr>                        
                          @endforeach
                          @endif
                      
                      </tbody>

                    </table>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

@endsection