routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
    Route::get('/', 'HomeController@admin')->name('admin');
    Route::resource('/user', 'UserController');
    Route::resource('/post', 'PostController');
    Route::resource('/comment', 'CommentController');
});



Route::get('/user', 'HomeController@user')->name('user');


Route::resource('/frontend', 'FrontendController');
Route::get('/', 'FrontendController@index')->name('homepage');
Route::post('/login1', 'FrontendController@login1')->name('login1');


Route::group(['prefix'=>'user'], function(){
    Route::resource('/userpanel','UserPanelController');
    Route::post('/user_post','UserPanelController@user_post')->name('user_post');
    Route::get('/user_update/{id}','UserPanelController@user_update')->name('user_update');
    Route::post('/user_store/{id}','UserPanelController@user_store')->name('user_store');
    Route::get('/my_post','UserPanelController@my_post')->name('my_post');
    Route::get('/members','UserPanelController@members')->name('members');
    Route::get('/search','UserPanelController@search')->name('search');
    Route::get('/user_details/{id}','UserPanelController@user_details')->name('user_details');
    Route::get('/post_details/{id}','UserPanelController@post_details')->name('post_details');
    Route::post('/insert_comment/{user_id}/{id}','UserPanelController@insert_comment')->name('insert_comment');

    Route::get('/delete_comment/{id}','UserPanelController@delete_comment')->name('delete_comment');

    Route::get('/friends','UserPanelController@friends')->name('friends');

    Route::get('/addfriend/{id}','UserPanelController@addfriend')->name('addfriend');


    Route::get('/cancel_request/{id}','UserPanelController@cancel_request')->name('cancel_request');
    Route::get('/confirm_request/{id}','UserPanelController@confirm_request')->name('confirm_request');

    Route::get('/sendmessage/{id}','UserPanelController@sendmessage')->name('sendmessage');

    Route::post('/insert_message/{id}','UserPanelController@insert_message')->name('insert_message');


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','age','contact','address','account','status','role','gender','image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getRules($option='add'){
        return [
            'name'=>'required|string',
            'email'=>(($option=='add')? 'required' : 'nullable').'|email',
            'age'=>'required|string',
            'address'=>'required|string',
            'contact'=>'required|string',
            'gender'=>'required|in:male,female,other',
            'role'=>'required|in:admin,user',
            'account'=>'required|in:activate,deactivate',
            'status'=>'required|in:active,inactive',
            'password'=>(($option=='add')? 'required' : 'nullable').'|string|confirmed',
        ];
    }



    public function user_info(){
        return $this->hasOne('App\User','id','user_id');
    }

    public function getUserDetails($id){
     return $this->with('user_info')->where('id',$id)->get();    
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    protected $user=null;
    public function __construct(User $user)
    {
        $this->user=$user;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=$this->user->where('id','!=',Request()->user()->id)->get();
        return view('admin.user.index')->with('userdata',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $rules=$this->user->getRules();
        $request->validate($rules);
        //dd($request);
        $data=$request->all();
        $data['password']=Hash::make($data['password']);

        $this->user=$this->user->fill($data);
        $this->user->save();

        if($this->user){
            request()->session()->flash('success','User added successfully');
        }
        else{
            request()->session()->flash('error','User not added at this time. Please try again');
        }

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->user=$this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','banner does not found');
            return redirect()->route('user.index');
        }
        return view('admin.user.form')->with('user_data',$this->user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules=$this->user->getRules('update');
        $request->validate($rules);
        //dd($request);
        $data=$request->all();

        if($request->change_password){
            $data['password']= Hash::make($data['password']);
        }else{
            unset($data['password']);
        }
        $this->user= $this->user->find($id);
        $this->user=$this->user->fill($data);
        $this->user->save();

        if($this->user){
            request()->session()->flash('success','User updated successfully');
        }
        else{
            request()->session()->flash('error','User not updated at this time. Please try again');
        }

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user =$this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','user not found');
            return redirect()->route('user.index');
        }
        $del =$this->user->delete();
        if($del){
            request()->session()->flash('success','user deleted successfully');
        }else{
            request()->session()->flash('error','problem while deleting User');
        }
        return redirect()->route('user.index');
    }
}

resources/views/admin/user/form.blade.php
@extends('layouts.admin_dashboard')

@section('scripts')
<script>
    $('#change_password').change(function(){
        var checked =$('#change_password').prop('checked');
        if(checked){
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('hidden');
        }else{
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('hidden');
        }
    });
</script>
@endsection

@section('content')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>User {{ isset($user_data) ? 'update' : 'add'}} </h3>

            </div>

            <div class="title_right">

            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2> User</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                    @if(isset($user_data))
                       {{Form::open(['url'=>route('user.update',$user_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
                            @method('PUT')


                        @else
                       {{Form::open(['url'=>route('user.store'),'class'=>'Form','enctype'=>'multipart/form-data']) }}
                    @endif
                       <div class="form-group row">
                            {{ Form::label('name', 'Name: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::text('name',@$user_data->name ,['class'=>'form-control','id'=>'name']) }}
                                @if($errors->has('name'))
                                <span class="alert-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{Form::label('address','Address:',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::text('address',@$user_data->address ,['class'=>'form-control']) }}
                                @if($errors->has('name'))
                                <span class="alert-danger">{{$errors->first('name')}}</span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row" style="display: {{ isset($user_data) ? 'none' : 'block' }}">
                            {{Form::label('email','Email:',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::text('email',@$user_data->email ,['class'=>'form-control'])}}
                                @if($errors->has('email'))
                                <span class="alert-danger">{{$errors->first('email')}}</span>
                                @endif
                            </div>
                        </div> 

                        <div class="form-group row">
                            {{ Form::label('contact', 'Contact: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::tel('contact',@$user_data->contact ,['class'=>'form-control','id'=>'contact']) }}
                                @if($errors->has('contact'))
                                <span class="alert-danger">{{ $errors->first('contact') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('age', 'Age: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::number('age',@$user_data->age ,['class'=>'form-control','id'=>'age']) }}
                                @if($errors->has('age'))
                                <span class="alert-danger">{{ $errors->first('age') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('gender', 'Gender: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::select('gender',['male'=>'Male','female'=>'Female','other'=>'Other'] ,@$user_data->gender ,['class'=>'form-control','id'=>'gender']) }}
                                @if($errors->has('gender'))
                                <span class="alert-danger">{{ $errors->first('gender') }}</span>
                                @endif
                            </div>
                        </div>
                      
                        
                        <div class="form-group row">
                            {{ Form::label('role', 'Role: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::select('role',['admin'=>'Admin','user'=>'User'] ,'',['class'=>'form-control','id'=>'role']) }}
                                @if($errors->has('role'))
                                <span class="alert-danger">{{ $errors->first('role') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('status', 'Status: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::select('status',['active'=>'Active','inactive'=>'Inactive'] ,@$user_data->status ,['class'=>'form-control','id'=>'status']) }}
                                @if($errors->has('status'))
                                <span class="alert-danger">{{ $errors->first('status') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group row">
                            {{ Form::label('account', 'Account: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::select('account',['activate'=>'Activate','deactivate'=>'deactivate'] ,@$user_data->account ,['class'=>'form-control','id'=>'account']) }}
                                @if($errors->has('account'))
                                <span class="alert-danger">{{ $errors->first('account') }}</span>
                                @endif
                            </div>
                        </div>
                        @if(isset($user_data))

                        <div class="form-group row" style=" isset($user_data) ? 'none' : 'block'  ">
                            {{ Form::label('change_password', 'Change password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::checkbox('change_password',1,false,['id'=>'change_password']) }} Yes
                                @if($errors->has('change_password'))
                                <span class="alert-danger">{{ $errors->first('change_password') }}</span>
                                @endif
                            </div>
                        </div>
                        @endif


                        <div class=" {{ isset($user_data)?'hidden':''}}" id="change_password_div">

                        <div class="form-group row" style=" isset($user_data) ? 'none' : 'block'  ">
                            {{ Form::label('password', 'Password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password',['id'=>'password','class'=>'form-control']) }}
                                @if($errors->has('password'))
                                <span class="alert-danger">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row" style=" isset($user_data) ? 'none' : 'block'  ">
                            {{ Form::label('confirm_password', 'Reenter password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password_confirmation',['id'=>'confirm_password','class'=>'form-control']) }}
                                @if($errors->has('confirm_password'))
                                <span class="alert-danger">{{ $errors->first('confirm_password') }}</span>
                                @endif
                            </div>
                        </div>

                        </div>

                        <div class="form-group row">
                            {{ Form::label('', ' ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-8">
                                {{Form::button('submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                                {{Form::button('reset',['class'=>'btn btn-danger','id'=>'reset','type'=>'reset']) }}
                               
                            </div>
                        </div>



                       {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin_dashboard')

@section('content')
 <!-- page content -->
 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
               <h3>Welcome to user page</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  
              <a href="{{ route('user.create')}}" class="btn btn-success pull-right"><i class="fas fa-plus"></i> Add user</a>
                  <div class="input-group">
                    
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>
            @include('admin.section.notification')

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>User Page</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <th>S.n</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Gender</th>
                        <th>Contact</th>
                        <th>Role</th>
                        <th>Action</th>
                      </thead>
                      <tbody>
                       
                          @if($userdata)
                          @foreach($userdata as $key=>$data)
                          <tr>
                          <td>{{ $key+1}}</td>
                          <td>{{ $data->name}}</td>
                          <td>{{ $data->address}}</td>
                          <td>{{ $data->email}}</td>
                          <td>{{ $data->gender}}</td>
                          <td>{{ $data->contact}}</td>
                          <td>{{ $data->role }}</td>
                          <td>
                          <a href="{{ route('user.edit',$data->id)}}" style="border-radius: 50%" class="btn btn-success">
                                        <i class="fas fa-pencil-alt"></i></a>
  

                            <form action="{{ route('user.destroy',$data->id)}}" onsubmit="return confirm('Are you sure to delete')" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger" style="border-radius: 50%">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                            
                          </td>
                          </tr>
                          @endforeach
                          @endif
                      
                      </tbody>

                    </table>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

@endsection